# Clippy linting configuration

# Cognitive complexity threshold
cognitive-complexity-threshold = 30

# Maximum number of lines in a function
too-many-lines-threshold = 100

# Maximum number of arguments in a function
too-many-arguments-threshold = 7

# Type complexity threshold
type-complexity-threshold = 250

# Maximum size for types on stack
trivial-copy-size-limit = 16

# Avoid common abbreviations in names
avoid-breaking-exported-api = true

# Disallow certain macros
disallowed-macros = []

# Maximum characters in a single expression
single-char-binding-names-threshold = 4