# Rust formatting configuration
# https://rust-lang.github.io/rustfmt/

# Basic formatting
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
edition = "2021"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Comments
normalize_comments = true
wrap_comments = true
comment_width = 80

# Code organization
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true

# Consistency
match_block_trailing_comma = true
trailing_comma = "Vertical"
overflow_delimited_expr = true

# Chain formatting
chain_width = 80
single_line_if_else_max_width = 80
